-- Seed Universities
INSERT INTO universities (name, domain, academic_calendar_json) VALUES
('IIT Madras', 'iitm.ac.in', '{"exam_months": [4, 11], "break_months": [5, 12]}'),
('IIT Bombay', 'iitb.ac.in', '{"exam_months": [4, 11], "break_months": [5, 12]}'),
('IIT Delhi', 'iitd.ac.in', '{"exam_months": [4, 11], "break_months": [5, 12]}'),
('IIT Roorkee', 'iitr.ac.in', '{"exam_months": [4, 11], "break_months": [5, 12]}'),
('BITS Pilani', 'bits-pilani.ac.in', '{"exam_months": [5, 11], "break_months": [6, 12]}'),
('NIT Trichy', 'nitt.edu', '{"exam_months": [4, 11], "break_months": [5, 12]}'),
('DTU', 'dtu.ac.in', '{"exam_months": [5, 12], "break_months": [6, 1]}');

-- Seed Opportunities
INSERT INTO opportunities (title, type, url, source, description, organizer, deadline, location, prize, tags, difficulty, is_closed) VALUES
('Smart India Hackathon 2026', 'hackathon', 'https://sih.gov.in', 'government', 'India''s biggest hackathon organized by the Ministry of Education. Solve real-world problems proposed by government ministries and industries.', 'Ministry of Education, Govt. of India', '2026-08-15', 'Pan India', '₹25 Lakhs', ARRAY['hackathon', 'government', 'innovation'], 'intermediate', false),
('Google Summer of Code 2026', 'oss', 'https://summerofcode.withgoogle.com', 'google', 'Global program focused on bringing more student developers into open source software development. Get paid to contribute to open source.', 'Google', '2026-04-01', 'Remote', 'Stipend $300-$1500', ARRAY['open-source', 'google', 'mentored'], 'intermediate', false),
('Microsoft Engage Mentorship', 'internship', 'https://microsoft.com/engage', 'microsoft', 'Mentorship program for engineering students. Get mentored by Microsoft engineers and work on real projects.', 'Microsoft', '2026-05-01', 'Remote', 'Stipend + PPO opportunity', ARRAY['mentorship', 'microsoft', 'internship'], 'beginner', false),
('Devfolio Season Kickoff', 'hackathon', 'https://devfolio.co', 'devfolio', 'Premier hackathon platform for Indian developers. Build, ship, and win prizes.', 'Devfolio', '2026-03-30', 'Hybrid', '₹5 Lakhs', ARRAY['hackathon', 'web3', 'ai'], 'intermediate', false),
('GitHub Campus Expert', 'ambassador', 'https://education.github.com/campus-experts', 'github', 'Build your technical community on campus. Get training, support, and resources from GitHub.', 'GitHub', '2026-06-01', 'Remote', 'Swag + Resources', ARRAY['community', 'github', 'leadership'], 'beginner', false),
('Google Generation Scholarship', 'scholarship', 'https://buildyourfuture.withgoogle.com/scholarships', 'google', 'Financial support for students in computer science. Must demonstrate academic excellence and leadership.', 'Google', '2026-05-15', 'Remote', '$10,000', ARRAY['scholarship', 'google', 'cs'], 'advanced', false),
('MLH Fellowship', 'internship', 'https://fellowship.mlh.io', 'mlh', 'Remote internship alternative for aspiring software engineers. Work on real open source projects.', 'Major League Hacking', '2026-04-15', 'Remote', 'Stipend $5000', ARRAY['internship', 'open-source', 'remote'], 'intermediate', false),
('Flipkart GRiD', 'internship', 'https://unstop.com/competitions/flipkart-grid', 'unstop', 'Engineering campus challenge by Flipkart. Solve real e-commerce problems.', 'Flipkart', '2026-07-01', 'Remote', '₹3 Lakhs + Internship', ARRAY['ecommerce', 'challenge', 'internship'], 'intermediate', false),
('SIH Software Edition', 'hackathon', 'https://sih.gov.in/software', 'government', 'Software edition of Smart India Hackathon. Build solutions for government problem statements.', 'Ministry of Education', '2026-09-01', 'Pan India', '₹1 Lakh', ARRAY['hackathon', 'government', 'software'], 'beginner', false),
('Hacktoberfest 2026', 'oss', 'https://hacktoberfest.com', 'digitalocean', 'Month-long celebration of open source. Make 4 pull requests to earn swag.', 'DigitalOcean', '2026-10-31', 'Remote', 'Swag', ARRAY['open-source', 'beginner-friendly', 'global'], 'beginner', false),
('JEE Advanced Prep Workshop', 'event', 'https://example.com/jee-workshop', 'custom', 'Free workshop series for JEE Advanced preparation by IIT alumni.', 'IIT Alumni Network', '2026-05-20', 'Online', 'Free', ARRAY['workshop', 'jee', 'preparation'], 'beginner', false),
('Amazon ML Summer School', 'internship', 'https://www.amazon.jobs/en/teams/university-programs', 'amazon', 'Intensive machine learning program for students. Learn from Amazon scientists.', 'Amazon', '2026-06-15', 'Remote', 'Certificate + Networking', ARRAY['ml', 'amazon', 'summer'], 'advanced', false),
('FOSSEE Summer Fellowship', 'internship', 'https://fossee.in', 'iitb', 'Summer fellowship by IIT Bombay''s FOSSEE project. Work on open source scientific computing tools.', 'IIT Bombay FOSSEE', '2026-04-30', 'Mumbai', '₹10,000/month', ARRAY['fellowship', 'science', 'iitb'], 'intermediate', false),
('Samsung PRISM', 'internship', 'https://samsung.com/prism', 'samsung', 'Research internship program by Samsung R&D India. Work on cutting-edge technology.', 'Samsung R&D', '2026-05-01', 'Bangalore/Hyderabad', 'Stipend + Certificate', ARRAY['research', 'samsung', 'internship'], 'advanced', false),
('Adobe Women in Tech', 'scholarship', 'https://adobe.com/women-in-tech', 'adobe', 'Scholarship program supporting women in technology. Includes mentorship and conference attendance.', 'Adobe', '2026-06-01', 'Remote', '$10,000', ARRAY['scholarship', 'women-in-tech', 'adobe'], 'intermediate', false),
('Dell Technologies Hackathon', 'hackathon', 'https://dell.com/hackathon', 'dell', 'Build innovative solutions for enterprise challenges. Open to all engineering students.', 'Dell Technologies', '2026-08-01', 'Bangalore', '₹5 Lakhs', ARRAY['hackathon', 'enterprise', 'dell'], 'intermediate', false),
('Postman Student Expert', 'ambassador', 'https://postman.com/student-expert', 'postman', 'Become a Postman Student Expert. Get certified in API development and lead workshops on campus.', 'Postman', '2026-07-15', 'Remote', 'Swag + Certification', ARRAY['api', 'ambassador', 'postman'], 'beginner', false),
('ICPC Regionals', 'hackathon', 'https://icpc.global', 'icpc', 'International Collegiate Programming Contest. Compete in teams of 3 to solve algorithmic problems.', 'ICPC Foundation', '2026-11-01', 'Various Cities', 'World Finals qualification', ARRAY['competitive-programming', 'algorithms', 'team'], 'advanced', false),
('GSoC Mentor Org Application', 'oss', 'https://summerofcode.withgoogle.com/get-started', 'google', 'Apply to become a GSoC mentoring organization. Guide students through open source contributions.', 'Google', '2026-02-15', 'Remote', 'Org stipend', ARRAY['open-source', 'mentoring', 'google'], 'advanced', false);
